sudo: required
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - docker pull docker.sunet.se/eduid/mongodb:latest
services:
  - docker
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install --index-url https://pypi.sunet.se -r test-requirements.txt
# command to run tests
script:
  - nosetests
